const cogQs = ["I really enjoy a task that involves coming up with new solutions to problems.",
"I believe that if I think hard enough, I will be able to achieve my goals in life.",
"I am very optimistic about my mental abilities.",
"I would prefer a task that is intellectual, difficult, and important to one that is somewhat important but does not require much thought.",
"I tend to set goals that can be accomplished only by expending considerable mental effort.",
"When something I read confuses me, I just put it down and forget it.",
"I take pride in the products of my reasoning.",
"I don't usually think about problems that others have found to be difficult.",
"I am usually tempted to put more thought into a task than the job minimally requires.",
"Learning new ways to think doesn't excite me very much",
"I am hesitant about making important decisions after thinking about them",
"I usually end up deliberating about issues even when they do not affect me personally",
"I prefer just to let things happen rather than try to understand why they turned out that way",
"I have difficulty thinking in new and unfamiliar situations",
"The idea of relying on thought to make my way to the top does not appeal to me.",
"The notion of thinking abstractly is not appealing to me.",
"I am an intellectual",
"I find it especially satisfying to complete an important task that required a lot of thinking and mental effort",
"I only think as hard as I have to.",
"I don't reason well under pressure.",
"I like tasks that require little thought once I've learned them.",
"I prefer to think about small, daily projects to long-term ones.",
"I would rather do something that requires little thought than something that is sure to challenge my thinking abilities.",
"I find little satisfaction in deliberating hard and for long hours.",
"I think primarily because I have to.",
"I more often talk with other people about the reasons for and possible solutions to international problems than about gossip or tidbits of what famous people are doing.",
"These days, I see little chance for performing well, even in 'intellectual' jobs, unless one knows the right people.",
"More often than not, more thinking just leads to more errors.",
"I don't like to have the responsibility of handling a situation that requires a lot of thinking.",
"I appreciate opportunities to discover the strengths and weaknesses of my own reasoning.",
"I feel relief rather than satisfaction after completing a task that required a lot of mental effort.",
"Thinking is not my idea of fun.",
"I try to anticipate and avoid situations where there is a likely chance I will have to think in depth about something.",
"I don't like to be responsible for thinking of what I should be doing with my life.",
"I prefer watching educational to entertainment programs.",
"I often succeed in solving difficult problems that I set out to solve.",
"I think best when those around me are very intelligent.",
"I am not satisfied unless I am thinking.",
"I prefer my life to be filled with puzzles that I must solve.",
"I would prefer complex to simple problems.",
"Simply knowing the answer rather than understanding the reasons for the answer to a problem is fine with me.",
"When I am figuring out a problem, what I see as the solution to a problem is more important than what others believe or say is the solution.",
"It's enough for me that something gets the job done, I don't care how or why it works.",
"Ignorance is bliss.",
"I enjoy thinking about an issue even when the results of my thought will have no effect on the outcome of the issue."
];
const cogAs = ["Strongly Disagree", "Slightly Disagree", "Neither Agree nor Disagree", "Slightly Agree", "Strongly Agree"];
const cogName = "Need for Cognition";

const closQs = ["I think that having clear rules and order at work is essential for success.",
"Even after I've made up my mind about something, I am always eager to consider a different opinion.",
"I don't like situations that are uncertain.",
"I dislike questions which could be answered in many different ways.",
"I like to have friends who are unpredictable.",
"I find that a well ordered life with regular hours suits my temperament.",
"I enjoy the uncertainty of going into a new situation without knowing what might happen.",
"When dining out, I like to go to places where I have been before so that I know what to expect.",
"I feel uncomfortable when I don't understand the reason why an event occurred in my life.",
"I feel irritated when one person disagrees with what everyone else in a group believes.",
"I hate to change my plans at the last minute.",
"I would describe myself as indecisive.",
"When I go shopping, I have difficulty deciding exactly what it is I want.",
"When faced with a problem I usually see the one best solution very quickly.",
"When I am confused about an important issue, I feel very upset.",
"I tend to put off making important decisions until the last possible moment.",
"I usually make important decisions quickly and confidently.",
"I have never been late for an appointment or work.",
"I think it is fun to change my plans at the last moment.",
"My personal space is usually messy and disorganized.",
"In most social conflicts, I can easily see which side is right and which is wrong.",
"I have never known someone I did not like.",
"I tend to struggle with most decisions.",
"I believe orderliness and organization are among the most important characteristics of a good student.",
"When considering most conflict situations, I can usually see how both sides could be right.",
"I don't like to be with people who are capable of unexpected actions.",
"I prefer to socialize with familiar friends because I know what to expect from them.",
"I think that I would learn best in a class that lacks clearly stated objectives and requirements.",
"When thinking about a problem, I consider as many different opinions on the issue as possible.",
"I don't like to go into a situation without knowing what I can expect from it.",
"I like to know what people are thinking all the time.",
"I dislike it when a person's statement could mean many different things.",
"It's annoying to listen to someone who cannot seem to make up his or her mind.",
"I find that establishing a consistent routine enables me to enjoy life more.",
"I enjoy having a clear and structured mode of life.",
"I prefer interacting with people whose opinions are very different from my own.",
"I like to have a plan for everything and a place for everything.",
"I feel uncomfortable when someone's meaning or intention is unclear to me.",
"I believe that one should never engage in leisure activities.",
"When trying to solve a problem I often see so many possible options that it's confusing.",
"I always see many possible solutions to problems I face.",
"I'd rather know bad news than stay in a state of uncertainty.",
"I feel that there is no such thing as an honest mistake.",
"I do not usually consult many different options before forming my own view.",
"I dislike unpredictable situations.",
"I have never hurt another person's feelings.",
"I dislike the routine aspects of my work (studies)."
];
const closAs = ["Strongly Disagree", "Moderately Disagree", "Slightly Disagree", "Neither Agree nor Disagree", "Slightly Agree", "Moderately Agree", "Strongly Agree"];
const closName = "Need for Closure";


Qs = [cogQs, closQs];
As = [cogAs, closAs];
names = [cogName, closName] ;